import { Calendar } from "@flowstack-ui/atom/calendar";
import { DateInput } from "@flowstack-ui/atom/date-input";
import { DatePicker } from "@flowstack-ui/atom/date-picker";
import { parseDate } from "@flowstack-ui/atom/date-value";
const referenceDate = parseDate("2026-09-05");
function Header() { return <Calendar.Header><Calendar.PrevTrigger>Previous</Calendar.PrevTrigger><Calendar.ViewTrigger /><Calendar.NextTrigger>Next</Calendar.NextTrigger></Calendar.Header>; }
export function CalendarWorkbench() { return <section aria-label="Calendar examples"><h3>1. Single selection</h3><Calendar.Root referenceDate={referenceDate}><Header /><Calendar.Grid aria-label="Single date" /></Calendar.Root><h3>2. Range</h3><Calendar.Root referenceDate={referenceDate} selectionMode="range"><Header /><Calendar.Grid aria-label="Range dates" /></Calendar.Root><h3>3. Multiple</h3><Calendar.Root referenceDate={referenceDate} selectionMode="multiple"><Header /><Calendar.Grid aria-label="Multiple dates" /></Calendar.Root></section>; }
export function DateInputWorkbench() { return <section aria-label="DateInput examples"><h3>1. Canonical form and reset</h3><form><DateInput.Root referenceDate={referenceDate} defaultValue={referenceDate} name="date" required><DateInput.Label>Date</DateInput.Label><DateInput.Control><DateInput.SegmentGroup><DateInput.Segments /></DateInput.SegmentGroup><DateInput.ClearTrigger>Clear</DateInput.ClearTrigger></DateInput.Control><DateInput.HiddenInput /></DateInput.Root><button type="reset">Reset</button><button type="submit">Validate</button></form><h3>2. Localized range</h3><DateInput.Root referenceDate={referenceDate} locale="fr-FR" selectionMode="range"><DateInput.Label>Début</DateInput.Label><DateInput.SegmentGroup><DateInput.Segments /></DateInput.SegmentGroup><DateInput.Label index={1}>Fin</DateInput.Label><DateInput.SegmentGroup index={1}><DateInput.Segments index={1} /></DateInput.SegmentGroup><DateInput.HiddenInput /><DateInput.HiddenInput index={1} /></DateInput.Root></section>; }
export function DatePickerWorkbench() { return <section aria-label="DatePicker examples"><h3>1. Shared entry and calendar</h3><DatePicker.Root referenceDate={referenceDate} name="delivery"><DatePicker.Label>Delivery</DatePicker.Label><DatePicker.Control><DatePicker.Input /><DatePicker.Trigger>Choose delivery date</DatePicker.Trigger><DatePicker.ClearTrigger>Clear</DatePicker.ClearTrigger></DatePicker.Control><DatePicker.Portal><DatePicker.Content aria-label="Delivery calendar"><DatePicker.Calendar><Header /><Calendar.Grid /></DatePicker.Calendar></DatePicker.Content></DatePicker.Portal></DatePicker.Root></section>; }
