export { createToastStore, defaultToastStore } from "./toast-store.js";
export type { ToastStore, ToastStoreOptions } from "./toast-store.js";
export { getDefaultToastDuration, normalizeToastDuration, normalizeMaxVisible, getToastRole, getToastAriaLive } from "./toast-values.js";
import { defaultToastStore } from "./toast-store.js";
export const getToasts = defaultToastStore.getToasts;
export const subscribeToasts = defaultToastStore.subscribe;
export const addToast = defaultToastStore.create;
export const dismissToast = defaultToastStore.dismiss;
export const updateToast = defaultToastStore.update;
export const pauseToast = defaultToastStore.pause;
export const resumeToast = defaultToastStore.resume;
