"use client";

import {
  ComboboxClear,
  ComboboxControl,
  ComboboxContent,
  ComboboxEmpty,
  ComboboxGroup,
  ComboboxInput,
  ComboboxItem,
  ComboboxLabel,
  ComboboxListbox,
  ComboboxLoading,
  ComboboxPortal,
  ComboboxRoot,
  ComboboxTrigger,
} from "./primitives/combobox/index.js";

export {
  ComboboxClear,
  ComboboxControl,
  ComboboxContent,
  ComboboxContextProvider,
  ComboboxEmpty,
  ComboboxGroup,
  ComboboxInput,
  ComboboxItem,
  ComboboxLabel,
  ComboboxListbox,
  ComboboxLoading,
  ComboboxPortal,
  ComboboxRoot,
  ComboboxTrigger,
  filterComboboxOptions,
  getComboboxOptionLabel,
  getNextComboboxValue,
  groupComboboxOptions,
  useComboboxContext,
} from "./primitives/combobox/index.js";
export type {
  ComboboxClearProps,
  ComboboxControlProps,
  ComboboxContentProps,
  ComboboxContextValue,
  ComboboxEmptyProps,
  ComboboxFilter,
  ComboboxGroupProps,
  ComboboxInputProps,
  ComboboxItemEntry,
  ComboboxItemProps,
  ComboboxLabelProps,
  ComboboxListboxProps,
  ComboboxLoadingProps,
  ComboboxOption,
  ComboboxOptionGroup,
  ComboboxPortalProps,
  ComboboxRootProps,
  ComboboxTriggerProps,
} from "./primitives/combobox/index.js";

export const Combobox = {
  Root: ComboboxRoot,
  Control: ComboboxControl,
  Input: ComboboxInput,
  Clear: ComboboxClear,
  Trigger: ComboboxTrigger,
  Portal: ComboboxPortal,
  Content: ComboboxContent,
  Listbox: ComboboxListbox,
  Group: ComboboxGroup,
  Label: ComboboxLabel,
  Item: ComboboxItem,
  Empty: ComboboxEmpty,
  Loading: ComboboxLoading,
} as const;
