"use client";

import {
  MenuCheckboxItem,
  MenuArrow,
  MenuContent,
  MenuGroup,
  MenuItemIndicator,
  MenuItem,
  MenuLabel,
  MenuPortal,
  MenuRadioGroup,
  MenuRadioItem,
  MenuRoot,
  MenuSeparator,
  MenuSubContent,
  MenuSubRoot,
  MenuSubTrigger,
} from "./primitives/menu/index.js";

export {
  MenuContextProvider,
  MenuCheckboxItem,
  MenuArrow,
  MenuContent,
  MenuGroup,
  MenuItemIndicator,
  MenuItem,
  MenuLabel,
  MenuPortal,
  MenuRadioGroup,
  MenuRadioGroupContextProvider,
  MenuRadioItem,
  MenuRoot,
  MenuSeparator,
  MenuSubContent,
  MenuSubContextProvider,
  MenuSubRoot,
  MenuSubTrigger,
  useMenuContext,
  useMenuRadioGroupContext,
  useMenuSubContext,
} from "./primitives/menu/index.js";
export type {
  MenuAlign,
  MenuCloseReason,
  MenuContextValue,
  MenuCheckboxItemProps,
  MenuArrowProps,
  MenuContentProps,
  MenuGroupProps,
  MenuItemIndicatorProps,
  MenuItemCheckedState,
  MenuItemProps,
  MenuLabelProps,
  MenuPortalProps,
  MenuRadioGroupProps,
  MenuRadioGroupContextValue,
  MenuRadioItemProps,
  MenuRootProps,
  MenuSeparatorProps,
  MenuSide,
  MenuSubContentProps,
  MenuSubContextValue,
  MenuSubRootProps,
  MenuSubTriggerProps,
} from "./primitives/menu/index.js";

export type {
  OutsideInteractionEvent,
  OutsideInteractionPointerType,
} from "./utils/interactions.js";

export const Menu = {
  Root: MenuRoot,
  Portal: MenuPortal,
  Content: MenuContent,
  Arrow: MenuArrow,
  Label: MenuLabel,
  Item: MenuItem,
  ItemIndicator: MenuItemIndicator,
  CheckboxItem: MenuCheckboxItem,
  RadioGroup: MenuRadioGroup,
  RadioItem: MenuRadioItem,
  Group: MenuGroup,
  Separator: MenuSeparator,
  Sub: MenuSubRoot,
  SubTrigger: MenuSubTrigger,
  SubContent: MenuSubContent,
} as const;
