"use client";

import {
  MultiSelectClearTrigger,
  MultiSelectArrow,
  MultiSelectContent,
  MultiSelectGroup,
  MultiSelectIcon,
  MultiSelectItem,
  MultiSelectItemIndicator,
  MultiSelectItemText,
  MultiSelectLabel,
  MultiSelectListbox,
  MultiSelectPortal,
  MultiSelectRootProvider,
  MultiSelectRoot,
  MultiSelectScrollDownButton,
  MultiSelectScrollUpButton,
  MultiSelectSeparator,
  MultiSelectTrigger,
  MultiSelectValue,
  MultiSelectViewport,
} from "./primitives/multi-select/index.js";

export {
  MultiSelectClearTrigger,
  MultiSelectArrow,
  MultiSelectContent,
  MultiSelectContextProvider,
  MultiSelectGroup,
  MultiSelectGroupContextProvider,
  MultiSelectIcon,
  MultiSelectItem,
  MultiSelectItemContextProvider,
  MultiSelectItemIndicator,
  MultiSelectItemText,
  MultiSelectLabel,
  MultiSelectListbox,
  MultiSelectPortal,
  MultiSelectRoot,
  MultiSelectScrollDownButton,
  MultiSelectScrollUpButton,
  MultiSelectSeparator,
  MultiSelectTrigger,
  MultiSelectValue,
  MultiSelectViewport,
  useMultiSelectGroupContext,
  useMultiSelectContext,
  useMultiSelectItemContext,
} from "./primitives/multi-select/index.js";
export type {
  MultiSelectClearTriggerProps,
  MultiSelectArrowProps,
  MultiSelectContentProps,
  MultiSelectContextValue,
  MultiSelectGroupContextValue,
  MultiSelectGroupProps,
  MultiSelectIconProps,
  MultiSelectItemProps,
  MultiSelectItemContextValue,
  MultiSelectItemIndicatorProps,
  MultiSelectItemTextProps,
  MultiSelectLabelProps,
  MultiSelectListboxProps,
  MultiSelectPortalProps,
  MultiSelectRootProps,
  MultiSelectScrollDownButtonProps,
  MultiSelectScrollUpButtonProps,
  MultiSelectSeparatorProps,
  MultiSelectTriggerProps,
  MultiSelectValueProps,
  MultiSelectViewportProps,
} from "./primitives/multi-select/index.js";

export type {
  OutsideInteractionEvent,
  OutsideInteractionPointerType,
} from "./utils/interactions.js";

export const MultiSelect = {
  ClearTrigger: MultiSelectClearTrigger,
  Root: MultiSelectRoot,
  RootProvider: MultiSelectRootProvider,
  Trigger: MultiSelectTrigger,
  Value: MultiSelectValue,
  Icon: MultiSelectIcon,
  Portal: MultiSelectPortal,
  Content: MultiSelectContent,
  Viewport: MultiSelectViewport,
  ScrollUpButton: MultiSelectScrollUpButton,
  ScrollDownButton: MultiSelectScrollDownButton,
  Listbox: MultiSelectListbox,
  Item: MultiSelectItem,
  ItemText: MultiSelectItemText,
  ItemIndicator: MultiSelectItemIndicator,
  Group: MultiSelectGroup,
  Label: MultiSelectLabel,
  Separator: MultiSelectSeparator,
  Arrow: MultiSelectArrow,
} as const;

export { useMultiSelect, MultiSelectRootProvider } from "./primitives/multi-select/index.js";
export type { UseMultiSelectReturn, MultiSelectRootProviderProps, SelectOption, SelectIds, SelectLifecycleOptions, SelectOutsideEvents } from "./primitives/multi-select/index.js";
