"use client";

import {
  PaginationEllipsis,
  PaginationItem,
  PaginationItems,
  PaginationList,
  PaginationNext,
  PaginationFirst,
  PaginationLast,
  PaginationPrevious,
  PaginationRoot,
  PaginationRootProvider,
  PaginationContextConsumer,
} from "./primitives/pagination/index.js";

export {
  PaginationContextProvider,
  PaginationContextConsumer,
  PaginationRootProvider,
  usePagination,
  PaginationEllipsis,
  PaginationItem,
  PaginationItems,
  PaginationList,
  PaginationNext,
  PaginationFirst,
  PaginationLast,
  PaginationPrevious,
  PaginationRoot,
  clampPaginationPage,
  getPaginationRange,
  usePaginationRange,
  usePaginationContext,
} from "./primitives/pagination/index.js";
export type {
  PaginationContextValue,
  PaginationIds,
  PaginationControlProps,
  PaginationEllipsisProps,
  PaginationItemProps,
  PaginationItemsProps,
  PaginationItemLabel,
  PaginationItemLabelDetails,
  PaginationListProps,
  PaginationRangeItem,
  PaginationRangeOptions,
  PaginationRootProps,
  PaginationRootProviderProps,
  UsePaginationProps,
  UsePaginationReturn,
} from "./primitives/pagination/index.js";

export const Pagination = {
  Root: PaginationRoot,
  RootProvider: PaginationRootProvider,
  Context: PaginationContextConsumer,
  List: PaginationList,
  Previous: PaginationPrevious,
  Items: PaginationItems,
  Item: PaginationItem,
  Ellipsis: PaginationEllipsis,
  Next: PaginationNext,
  First: PaginationFirst,
  Last: PaginationLast,
} as const;
