"use client";

import {
  PopoverAnchor,
  PopoverArrow,
  PopoverClose,
  PopoverContent,
  PopoverDescription,
  PopoverPortal,
  PopoverRoot,
  PopoverTrigger,
  PopoverTitle,
} from "./primitives/popover/index.js";

export {
  getPopoverArrowGeometry,
  PopoverAnchor,
  PopoverArrow,
  PopoverClose,
  PopoverContentContextProvider,
  PopoverContent,
  PopoverContextProvider,
  PopoverDescription,
  PopoverPortal,
  PopoverRoot,
  PopoverTrigger,
  PopoverTitle,
  usePopoverContentContext,
  usePopoverContext,
} from "./primitives/popover/index.js";
export type {
  PopoverAlign,
  PopoverAnchorProps,
  PopoverArrowGeometry,
  PopoverArrowProps,
  PopoverCloseProps,
  PopoverContentContextValue,
  PopoverContentProps,
  PopoverCloseReason,
  PopoverContextValue,
  PopoverDescriptionProps,
  PopoverFinalFocusDetails,
  PopoverFocusTarget,
  PopoverHeadingLevel,
  PopoverInitialFocusDetails,
  PopoverInteractionType,
  PopoverOpenReason,
  PopoverPortalProps,
  PopoverRootProps,
  PopoverSide,
  PopoverTriggerMode,
  PopoverTriggerProps,
  PopoverTitleProps,
} from "./primitives/popover/index.js";

export const Popover = {
  Root: PopoverRoot,
  Anchor: PopoverAnchor,
  Trigger: PopoverTrigger,
  Portal: PopoverPortal,
  Content: PopoverContent,
  Title: PopoverTitle,
  Description: PopoverDescription,
  Close: PopoverClose,
  Arrow: PopoverArrow,
} as const;
