"use client";

import {
  SelectArrow,
  SelectContent,
  SelectGroup,
  SelectIcon,
  SelectItem,
  SelectItemIndicator,
  SelectItemText,
  SelectLabel,
  SelectListbox,
  SelectPortal,
  SelectRoot,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  SelectViewport,
} from "./primitives/select/index.js";

export {
  SelectArrow,
  SelectContent,
  SelectContextProvider,
  SelectGroup,
  SelectGroupContextProvider,
  SelectIcon,
  SelectItem,
  SelectItemContextProvider,
  SelectItemIndicator,
  SelectItemText,
  SelectLabel,
  SelectListbox,
  SelectPortal,
  SelectRoot,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  SelectViewport,
  useSelectGroupContext,
  useSelectContext,
  useSelectItemContext,
} from "./primitives/select/index.js";
export type {
  SelectArrowProps,
  SelectContentProps,
  SelectContextValue,
  SelectGroupContextValue,
  SelectGroupProps,
  SelectIconProps,
  SelectItemProps,
  SelectItemContextValue,
  SelectItemIndicatorProps,
  SelectItemTextProps,
  SelectLabelProps,
  SelectListboxProps,
  SelectPortalProps,
  SelectRootProps,
  SelectScrollDownButtonProps,
  SelectScrollUpButtonProps,
  SelectSeparatorProps,
  SelectTriggerProps,
  SelectValueProps,
  SelectViewportProps,
} from "./primitives/select/index.js";

export const Select = {
  Root: SelectRoot,
  Trigger: SelectTrigger,
  Value: SelectValue,
  Icon: SelectIcon,
  Portal: SelectPortal,
  Content: SelectContent,
  Viewport: SelectViewport,
  ScrollUpButton: SelectScrollUpButton,
  ScrollDownButton: SelectScrollDownButton,
  Listbox: SelectListbox,
  Item: SelectItem,
  ItemText: SelectItemText,
  ItemIndicator: SelectItemIndicator,
  Group: SelectGroup,
  Label: SelectLabel,
  Separator: SelectSeparator,
  Arrow: SelectArrow,
} as const;
