"use client";

import {
  SelectClearTrigger,
  SelectArrow,
  SelectContent,
  SelectGroup,
  SelectIcon,
  SelectItem,
  SelectItemIndicator,
  SelectItemText,
  SelectLabel,
  SelectListbox,
  SelectPortal,
  SelectRootProvider,
  SelectRoot,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  SelectViewport,
} from "./primitives/select/index.js";

export {
  SelectClearTrigger,
  SelectArrow,
  SelectContent,
  SelectContextProvider,
  SelectGroup,
  SelectGroupContextProvider,
  SelectIcon,
  SelectItem,
  SelectItemContextProvider,
  SelectItemIndicator,
  SelectItemText,
  SelectLabel,
  SelectListbox,
  SelectPortal,
  SelectRoot,
  SelectScrollDownButton,
  SelectScrollUpButton,
  SelectSeparator,
  SelectTrigger,
  SelectValue,
  SelectViewport,
  useSelectGroupContext,
  useSelectContext,
  useSelectItemContext,
} from "./primitives/select/index.js";
export type {
  SelectClearTriggerProps,
  SelectArrowProps,
  SelectContentProps,
  SelectContextValue,
  SelectGroupContextValue,
  SelectGroupProps,
  SelectIconProps,
  SelectItemProps,
  SelectItemContextValue,
  SelectItemIndicatorProps,
  SelectItemTextProps,
  SelectLabelProps,
  SelectListboxProps,
  SelectPortalProps,
  SelectRootProps,
  SelectScrollDownButtonProps,
  SelectScrollUpButtonProps,
  SelectSeparatorProps,
  SelectTriggerProps,
  SelectValueProps,
  SelectViewportProps,
} from "./primitives/select/index.js";

export type {
  OutsideInteractionEvent,
  OutsideInteractionPointerType,
} from "./utils/interactions.js";

export const Select = {
  ClearTrigger: SelectClearTrigger,
  Root: SelectRoot,
  RootProvider: SelectRootProvider,
  Trigger: SelectTrigger,
  Value: SelectValue,
  Icon: SelectIcon,
  Portal: SelectPortal,
  Content: SelectContent,
  Viewport: SelectViewport,
  ScrollUpButton: SelectScrollUpButton,
  ScrollDownButton: SelectScrollDownButton,
  Listbox: SelectListbox,
  Item: SelectItem,
  ItemText: SelectItemText,
  ItemIndicator: SelectItemIndicator,
  Group: SelectGroup,
  Label: SelectLabel,
  Separator: SelectSeparator,
  Arrow: SelectArrow,
} as const;

export { useSelect, SelectRootProvider } from "./primitives/select/index.js";
export type { UseSelectReturn, SelectRootProviderProps, SelectOption, SelectIds, SelectLifecycleOptions, SelectOutsideEvents } from "./primitives/select/index.js";
