"use client";

import {
  SliderRange,
  SliderRoot,
  SliderRootProvider,
  SliderThumb,
  SliderTrack,
  SliderContext,
  SliderControl,
  SliderDraggingIndicator,
  SliderHiddenInput,
  SliderLabel,
  SliderMarker,
  SliderMarkerGroup,
  SliderMarkerIndicator,
  SliderMarkerLabel,
  SliderValueText,
} from "./primitives/slider/index.js";

export {
  SliderRange,
  SliderRoot,
  SliderRootProvider,
  SliderThumb,
  SliderTrack,
  SliderContext,
  SliderControl,
  SliderDraggingIndicator,
  SliderHiddenInput,
  SliderLabel,
  SliderMarker,
  SliderMarkerGroup,
  SliderMarkerIndicator,
  SliderMarkerLabel,
  SliderValueText,
  SliderContextProvider,
  clampSliderValue,
  applySliderCollision,
  getClosestThumbIndex,
  getSliderRangeOffsetStyle,
  getSliderThumbOffsetStyle,
  percentToValue,
  normalizeSliderConfig,
  normalizeSliderValues,
  snapToStep,
  useSliderContext,
  useSlider,
  valueToPercent,
} from "./primitives/slider/index.js";
export type {
  SliderCollisionBehavior,
  SliderController,
  SliderContextProps,
  SliderControlProps,
  SliderDraggingIndicatorDetails,
  SliderDraggingIndicatorProps,
  SliderHiddenInputMode,
  SliderHiddenInputProps,
  SliderLabelProps,
  SliderMarkerGroupProps,
  SliderMarkerProps,
  SliderContextValue,
  SliderOrientation,
  SliderOrigin,
  SliderRangeProps,
  SliderRangeState,
  SliderRootProps,
  SliderRootProviderProps,
  SliderThumbAlignment,
  SliderThumbBehaviorProps,
  SliderThumbProps,
  SliderThumbState,
  SliderThumbSize,
  SliderTrackProps,
  SliderValue,
  SliderValueTextDetails,
  SliderValueTextProps,
  UseSliderProps,
} from "./primitives/slider/index.js";

export const Slider = {
  Root: SliderRoot,
  RootProvider: SliderRootProvider,
  Context: SliderContext,
  Control: SliderControl,
  Track: SliderTrack,
  Range: SliderRange,
  Thumb: SliderThumb,
  Label: SliderLabel,
  ValueText: SliderValueText,
  MarkerGroup: SliderMarkerGroup,
  Marker: SliderMarker,
  MarkerIndicator: SliderMarkerIndicator,
  MarkerLabel: SliderMarkerLabel,
  DraggingIndicator: SliderDraggingIndicator,
  HiddenInput: SliderHiddenInput,
} as const;
