"use client";

export {
  TagsInput,
  TagsInputRoot,
  TagsInputRootProvider,
  TagsInputContext,
  TagsInputLabel,
  TagsInputControl,
  TagsInputInput,
  TagsInputItem,
  TagsInputItemPreview,
  TagsInputItemText,
  TagsInputItemInput,
  TagsInputItemDeleteTrigger,
  TagsInputClearTrigger,
  TagsInputHiddenInput,
  useTagsInputCombobox,
  type TagsInputRootProps,
  type TagsInputRootProviderProps,
  type TagsInputInputProps,
  type TagsInputItemProps,
  type TagsInputItemInputProps,
  type TagsInputTriggerProps,
} from "./primitives/tags-input/TagsInput.js";
export {
  useTagsInput,
  useTagsInputContext,
  type TagsInputOptions,
  type TagsInputController,
  type TagsInputItemState,
  type TagsInputInvalidReason,
  type TagsInputValueChangeDetails,
  type TagsInputInputValueChangeDetails,
  type TagsInputInvalidDetails,
  type TagsInputOutsideEvent,
  type TagsInputTranslations,
} from "./primitives/tags-input/controller.js";
