"use client";

import {
  ToastAction,
  ToastCancel,
  ToastClose,
  ToastDescription,
  ToastProvider,
  ToastRoot,
  ToastTitle,
  ToastViewport,
} from "./primitives/toast/index.js";

export {
  addToast,
  dismissToast,
  getDefaultToastDuration,
  getToastAriaLive,
  getToastRole,
  getToasts,
  normalizeMaxVisible,
  normalizeToastDuration,
  pauseToast,
  resumeToast,
  subscribeToasts,
  toast,
  toastProviderDefaults,
  ToastAction,
  ToastCancel,
  ToastClose,
  ToastDescription,
  ToastProvider,
  ToastProviderContextProvider,
  ToastRoot,
  ToastRootContextProvider,
  ToastViewportContextProvider,
  ToastTitle,
  ToastViewport,
  updateToast,
  useToastProviderContext,
  useToastRootContext,
  useToastViewportContext,
  useToastStore,
} from "./primitives/toast/index.js";
export type {
  ToastActionData,
  ToastActionProps,
  ToastCancelProps,
  ToastCloseProps,
  ToastData,
  ToastDescriptionProps,
  ToastId,
  ToastOptions,
  ToastPosition,
  ToastPromiseOptions,
  ToastProviderContextValue,
  ToastProviderProps,
  ToastRootContextValue,
  ToastRootProps,
  ToastState,
  ToastTitleProps,
  ToastType,
  ToastViewportProps,
  ToastViewportRenderState,
  ToastViewportContextValue,
  ToastSwipeDirection,
  ToastSwipeState,
  ToastUpdateOptions,
} from "./primitives/toast/index.js";

export const Toast = {
  Provider: ToastProvider,
  Root: ToastRoot,
  Title: ToastTitle,
  Description: ToastDescription,
  Action: ToastAction,
  Cancel: ToastCancel,
  Close: ToastClose,
  Viewport: ToastViewport,
} as const;
