"use client";

import {
  TreeGridBody,
  TreeGridTrigger,
  TreeGridColumnResizeHandle,
  TreeGridCaption,
  TreeGridCell,
  TreeGridColumn,
  TreeGridColumnGroup,
  TreeGridColumnHeader,
  TreeGridFooter,
  TreeGridHeader,
  TreeGridRoot,
  TreeGridRow,
  TreeGridRowHeader,
} from "./primitives/tree-grid/index.js";

export {
  TreeGridColumnResizeHandle,
  TreeGridTrigger,
  TreeGridBody,
  TreeGridCaption,
  TreeGridCell,
  TreeGridColumn,
  TreeGridColumnGroup,
  TreeGridColumnHeader,
  TreeGridContextProvider,
  TreeGridFooter,
  TreeGridHeader,
  TreeGridRoot,
  TreeGridRow,
  TreeGridRowContextProvider,
  TreeGridRowHeader,
  useTreeGridContext,
  useTreeGridRowContext,
} from "./primitives/tree-grid/index.js";
export type {
  TreeGridColumnResizeHandleProps,
  TreeGridTriggerProps,
  TreeGridBodyProps,
  TreeGridCaptionProps,
  TreeGridCellCoordinates,
  TreeGridCellData,
  TreeGridCellProps,
  TreeGridColumnGroupProps,
  TreeGridColumnProps,
  TreeGridColumnHeaderProps,
  TreeGridContextValue,
  TreeGridFooterProps,
  TreeGridHeaderProps,
  TreeGridRootProps,
  TreeGridRowContextValue,
  TreeGridRowData,
  TreeGridRowEntry,
  TreeGridRowHeaderProps,
  TreeGridRowProps,
  TreeGridSelectionMode,
  TreeGridSelectionValue,
  TreeGridSortDirection,
} from "./primitives/tree-grid/index.js";

export const TreeGrid = {
  ColumnResizeHandle: TreeGridColumnResizeHandle,
  Trigger: TreeGridTrigger,
  Root: TreeGridRoot,
  ColumnGroup: TreeGridColumnGroup,
  Column: TreeGridColumn,
  Header: TreeGridHeader,
  Body: TreeGridBody,
  Footer: TreeGridFooter,
  Row: TreeGridRow,
  ColumnHeader: TreeGridColumnHeader,
  RowHeader: TreeGridRowHeader,
  Cell: TreeGridCell,
  Caption: TreeGridCaption,
} as const;
